# Config file for automatic testing at travis-ci.org
sudo: false
language: python
python:
  - "3.5"
  - "2.7"

install: 
  - pip install tox
  - pip install coveralls
script: tox
notifications:
  email: false
after_success:
  coveralls
